# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 남혁준
title: 클라우드 엔지니어
email: hyukjuner@gmail.com
website: medium.com/@hyukjuner

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: hyukjuner
github_username:  hyukjuns
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: hyukjun
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: medium
  icon: fas fa-globe
  url: https://medium.com/@hyukjuner
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/mypic_sky.jpeg
about_content: | # this will include new lines to allow paragraphs
  <mark>남혁준</mark>, <mark>Azure Cloud Engineer</mark>

  안녕하세요 Azure 클라우드 엔지니어 남혁준 입니다.

  현재 Azure 인프라 매니지드 서비스 센터에서 운영 2팀의 파트리드를 맡고 있습니다. 

  고객사의 Azure Cloud 인프라를 안정적으로 운영하면서, 인프라 장애 발생시 신속한 트러블슈팅과 기술 지원을 하고있습니다.

  이외에도, 인프라 구축 및 구성 지원, 인프라 관리 자동화 지원, 랜딩존 및 Azure DevOps CI/CD 교육, IaC 기반 사내 프로젝트 등의 업무를 수행합니다.
  
content:
  - title: 업무경험 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cloocus
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: 클라우드 엔지니어
        caption: >
          2020.11 ~ Present
        description: | # this will include new lines to allow paragraphs
          - 20여개 고객사 인프라 운영 및 모니터링, 장애대응, 장애분석, 기술지원, 컨설팅, 비용관리
          - 효율적인 클라우드 인프라 관리를 위한 자동화 업무 지원
          - 인프라 구축 및 아키텍쳐 컨설팅, PoC, 교육 세미나 진행
          - 운영팀 및 사내 프로젝트 리딩 (운영팀 파트리드(2022.11~), IaC 기반 사내 프로젝트 리딩)
  - title: 업무역량 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 1. 인프라 운영
        sub_title: Azure Cloud Operation
        caption: 상시업무
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - **팀 리딩 및 커뮤니케이션**
    
            5명 규모 팀을 리딩 하면서 팀원간의 협업을 위한 의사소통 문화 조성, 팀원 기술 코칭, 기술 발전 방향성 제시
            
          - **클라우드 인프라 운영 및 기술지원, 장애 대응 및 분석**
            
            모니터링 / 유지보수 / 기술지원 / 비용분석 / 주,야간 긴급 장애 트러블슈팅 / 장애분석 / 이벤트 트래픽 대응
            
          - **클라우드 인프라 구성/변경 지원 및 가이드**
            
            Azure IaaS / PaaS / Network(+Hybrid) 환경 구성 및 변경 작업, 모니터링 및 로깅 환경 구성, 구축간 트러블슈팅 지원
            
          - **클라우드 인프라 자동화 지원**
            
            Shell Script, Azure DevOps Pipeline, Azure Policy, 이벤트 기반 서비스 및 함수 서비스를 사용한 인프라 자동화 환경 구성 지원
          
          ---
      
      - layout: left
        title: 2. 인프라 구축
        sub_title: Azure Cloud Architect
        # caption: 인프라 운영 업무와 병행해서 신규 인프라 구축 프로젝트 및 PoC 프로젝트에 참여하거나 프로젝트 PM을 수행하였습니다.
        # quote: >
        #   인프라 운영 업무와 병행해서 신규 인프라 구축 프로젝트 및 PoC 프로젝트에 참여하거나 프로젝트 PM을 수행하였습니다.
        description: | # this will include new lines to allow paragraphs
          - **고객사 신규 클라우드 인프라 구축 프로젝트 리딩, PM**
    
              기간: 2023.04~05
              
              주제: Azure Network 및 VirtualMachine, Storage, AKS, Database 환경 구축
              
              역할: 안정성을 고려한 네트워크 및 인프라 아키텍쳐 설계, 구성 테스트 및 배포 진행, 일정관리, 고객사 및 내부 담당자간 커뮤니케이션 조율    
          
          - **고객사 AVD 환경 구축 프로젝트, 팀원**
              
              기간: 2022.07~08
              
              주제: Azure Virtual Desktop 환경 구축 프로젝트
              
              역할: AVD 환경을 위한 Azure FW 설계 및 구축 진행(FW 정책 및 라우팅 구성), Azure AD 조건부 엑세스를 사용한 IP Based AVD 접근제어 환경 구성
              
          - **Azure DevOps를 사용한 CI/CD 구축, PoC 담당자**
              
              기간: 2022.01

              주제: Azure DevOps 플랫폼을 사용하여 Azure VMSS 에 Packer로 만든 가상머신 이미지를 배포하고 업그레이드 하는 CI/CD 파이프라인 구축

              역할: 데모 CI/CD 파이프라인 구축 및 배포 시연을 위한 세션 진행          
          
          ---

      - layout: left
        title: 3. 사내 프로젝트 팀 리딩
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 사내프로젝트
        caption: LandingZone, Terraform, Terraform module
        # quote: >
        #   사내 프로젝트, 2022.01~2022.09
        description: | # this will include new lines to allow paragraphs
          - **랜딩존 및 IaC 기반 프로젝트**
    
            기간: 2022.01~2023.05
            
            팀목표: CAF(Cloud Adoption Framework)기반 랜딩존 설계, 운영 관리를 위한 대시보드 기획 및 구성
            
            역할: 팀 리딩, 테라폼 코드 설계 및 모듈화, 모듈 버전관리, git 협업 체계 도입, 프로젝트 문서화 및 일정관리

          ---

      - layout: left
        title: 4. 클라우드 및 CI/CD 교육, 세미나 진행
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 세미나, 교육, PoC
        caption: Azure Landing Zone, Azure DevOps
        # quote: >
        #   사내 프로젝트, 2022.09 ~ 2023.05
        description: | # this will include new lines to allow paragraphs
          - **Azure 랜딩존 소개 세미나**
    
              고객사를 대상으로한 Azure 클라우드를 위한 표준 랜딩존 소개 및 발표 진행
              
          - **Azure DevOps를 교육**
              
              고객사를 대상으로한 Azure DevOps CI/CD 핸즈온 교육과 PoC 진행

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Azure Cloud
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - **Governance**: Azure AD, Management Group, Azure Policy
          - **Networking**: Azure Virtual Network, Azure DNS, Azure VPN, Azure vWAN, Azure Application Gateway, Azure Load Balancer, Private Endpoint/Link, Network Security Group, Azure Firewall
          - **Computing**: Azure Virtual Machine, Azure Virtual Machine Scale Set, Azure App Service, Azure Functions, Azure Kubernetes Service
          - **Storage & Security**: StorageAccount(File share, Blob), Azure Key Vault, Azure Container Registry
          - **Monitoring & Logging**: Azure Monitor, Azure Log Analytics, Resource Graph, KQL, Resource Diagnostic Setting
          - **Event Service**: EventGrid, EventHub
      - layout: left
        title: Infrastructure
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - **OS**: Linux(Ubuntu, CentOS), Windows
          - **Understanding** Virtualization, Network, Web Server (Apache, NGINX)
      - layout: left
        title: DevOps
        # caption: 2010 - 2013
        # sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - **IaC**: Terraform
          - **Container:** Docker, Kubernetes
          - **Automation**: Shell Script, Python
          - **CI/CD**: Azure DevOps
  - title: Certificate
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: Cloud and DevOps
        sub_title: Microsoft Azure, Hashicorp Terraform, Kubernetes
        # caption: 2022.01.24 ~
        # link: https://www.credly.com/badges/3ff69143-2487-4563-87a1-32a186f26578/public_url
        # link_text: badge - credly.com
        description: | 
          | Azure Administrator Associate        | Azure Solutions Architect Expert | Terraform Associate  | CKA: Certified Kubernetes Administrator | CKAD: Certified Kubernetes Application Developer
          |:-------------:|:-------------:|:------------:|:------------:|:------------:|
          | ![azureadmin](images/azureadmin.png)     | ![azuresa](images/azuresa.png) | ![terraform](images/terraform.png) | ![cka](images/cka.png) | ![ckad](images/ckad.png)
          | Microsoft    | Microsoft | HashiCorp | The Linux Foundation | The Linux Foundation
          | [Badge](https://www.credly.com/badges/b5616a4d-d730-4128-a07d-9e2014702bf1/public_url)    | [Badge](https://www.credly.com/badges/3ff69143-2487-4563-87a1-32a186f26578/public_url) | [Badge](https://www.credly.com/badges/be4ebf31-97f2-4252-aefa-0725cab291a4/public_url) | [Badge](https://www.credly.com/badges/2ef2b693-dd9b-4ca9-aa6c-88b075e5fc10/public_url) | [Badge](https://www.credly.com/badges/fcf74bd7-3dae-4fa8-b353-8152acca3d8a/public_url)

  - title: Side Project
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: 기술블로그
        link: https://medium.com/@hyukjuner
        link_text: https://medium.com/@hyukjuner
        description: | 
          - 개인적으로 공부하거나, 업무 경험을 통해 배운 내용을 정리해 두는 장소입니다.
          - How to Guide, Tutorial, 기술 소개 등 글의 속성을 나눠 글을 작성하고 있습니다.
      - layout: left
        title: 데모 및 기술 문서화
        link: https://github.com/hyukjuns
        link_text: https://github.com/hyukjuns
        description: | 
          - 개인적인 학습 및 작업물 들을 정리하고 문서화 하고, 코드 작업물을 관리합니다.
          - 개인적인 호기심으로 여러가지 인프라 구성을 테스트 하거나, 데모 및 테스트용 작업물을 관리합니다. 
  - title: 교육 활동
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: 클라우드 전문교육
        sub_title: CCCR
        caption: 2020.04 ~ 2020.11
        # link: https://medium.com/@hyukjuner
        # link_text: https://medium.com/@hyukjuner
        description: | 
          - 리눅스 및 가상화, IaC, 컨테이너 환경(Docker,K8s) 기술 교육
          - 폐쇄망환경에서 OpenShift Conatiner Platform 4.4.17 구축 프로젝트 수행
          - [Disconnect Openshift Container Platform 구축 및 CI/CD Pipeline](https://github.com/cccr2guro-redhat/Disconnected-Openshift4)
      - layout: left
        title: Programming Lab
        sub_title: ESC, 학부연구실
        caption: 2017.01~2018.07 
        # link: https://medium.com/@hyukjuner
        # link_text: https://medium.com/@hyukjuner
        description: | 
          - C, Java 기반 알고리즘 학습 및 화자인식 머신러닝 연구, 학술대회 참가
          - [ESC Machine learning](https://github.com/hyukjuns/esc-machine-learning)
  - title: 외부 활동
    layout: text
    content: |
      - [유튜브 - 운영플랫폼 세미나](https://www.youtube.com/watch?v=ud2oFqGEhqA)
      - [잡플래닛 인터뷰](https://www.jobplanet.co.kr/contents/news-1629)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
