# Site
repository: hyukjuns/hyukjns.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 남혁준
title: 클라우드 엔지니어 | To be DevOps
email: hyukjuner@gmail.com
website: medium.com/@hyukjuner

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  hyukjuns
linkedin_username: hyukjun

# Additional icon links
additional_links:
- title: medium
  icon: fab fa-medium
  url: https://medium.com/@hyukjuner

about_profile_image: images/mypic_sky.jpeg
about_content: | # this will include new lines to allow paragraphs

  현재 Azure Managed Service 그룹의 3년 차 클라우드 엔지니어로서 고객들의 클라우드 인프라를 운영하고 있습니다. 안정적인 클라우드 운영 환경을 구성하고, 다양한 장애 상황을 해결하는 소방수 역할과 동시에 클라우드 인프라 설계와 구축 그리고 거버넌스 관리까지 클라우드의 다양한 영역을 매니징 하고 있습니다.

  제 성장 목표인 DevOps 엔지니어가 되기 위해 운영 업무를 통해 문제 해결 능력을 키워가고 있으며, 인프라 자동화와 Terraform을 사용한 IaC, Ci/CD 파이프라인 관련 업무를 수행하면서 DevOps 역량을 키워나가고 있습니다. Linux와 Container, Kubernetes에 관심이 많으며, 꾸준한 공부를 바탕으로 실제 고객의 Kubernetes 환경 운영과 기술 지원을 수행하고 있습니다.

  대고객 업무와 다양한 구성원과의 협업을 통해 소통의 중요성을 이해하고 있으며, 올바른 소통과 협업을 통해 빠르게 문제를 해결하고 더 나은 서비스를 제공하기 위해 노력하고 있습니다. 현재 적은 연차이지만 운영팀의 파트 리드로서 팀원 들의 성장을 돕고 올바른 소통과 협업 문화를 이루기 위해 항상 노력하고 있습니다.

# Work Experience
content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Azure Cloud
        description: | # this will include new lines to allow paragraphs
          - **Networking**: Virtual Network, Application Gateway, Load Balancer, Azure DNS, Azure VPN, Azure vWAN, Private Endpoint, NSG, UDR, Azure Firewall
          - **Computing**: Virtual Machine, Virtual Machine Scale Set, App Service, Azure Kubernetes Service
          - **Storage & Security**: Storage Account(FileShare, Blob), Key Vault, Azure Container Registry
          - **Monitoring & Logging**: Azure Monitor, Log Analytics, KQL
          - **Event Service**: EventGrid, EventHub
          - **Governance**: Azure AD, Management Group, Azure Policy, Cost Management
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - **OS**: Linux (Ubuntu, CentOS)
          - **Container**: Docker, Kubernetes
          - **IaC**: Terraform
          - **Scripting & Dev**: Shell Script, Python
          - **CI/CD:** Azure DevOps Pipelines
          - **VCS**: Git, Github
      - layout: left
        title: ETC
        description: | # this will include new lines to allow paragraphs
          - Azure Cloud Design and Operational capabilities
          - Cloud infrastructure and network problem solving capabilities
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cloocus (클루커스)
        sub_title: Managed Service Center
        caption: |
          Azure 운영 2팀 파트리드

          (2022.11 ~ 현재)

          클라우드 엔지니어 

          (2020.11 ~ 2022.11)
        description: | # this will include new lines to allow paragraphs
          - Azure 클라우드 인프라 운영, 모니터링 및 장애대응, 기술지원, 인프라 설계 및 구축, 클라우드 거버넌스 관리
          - Azure 클라우드 인프라 자동화 업무
          - Kubernetes(AKS) 환경 운영 및 기술지원
          - Terraform 기반의 프로젝트 리딩, Terraform 모듈 설계
          - Azure DevOps를 사용한 CI/CD 파이프라인 PoC 및 교육
          - 9명 규모 운영 팀 리딩

  - title: 업무역량 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: 1. Azure 클라우드 및 Kubernetes 인프라 운영 및 구축 역량
        sub_title: Azure Cloud Managed Service
        caption: Azure Cloud, Kubernetes
        description: | # this will include new lines to allow paragraphs
          - 다양한 고객의 Azure 인프라 온보딩, 인프라 운영, 장애상황 대응
          - Azure IaaS, PaaS, Network 관련 기술지원 및 인프라 구축 업무 수행
          - L4~L7 부하분산 서비스 구성 지원, Azure VPN을 사용한 하이브리드 네트워크 구성 지원
          - Kubernetes(AKS) 인프라 운영 및 장애대응, 기술지원, Azure Monitor와 Datadog을 사용한 클러스터 모니터링
          - Azure Monitor, Log Analytics를 사용한 모니터링 환경 구성 및 운영, TIG Stack, Datadog 등 모니터링 솔루션 사용경험 보유
          - Azure AD, Azure Policy를 활용한 클라우드 거버넌스 및 비용 관리 수행

          ---
      
      - layout: top
        title: 2. IaC 활용 역량 (Terraform)
        sub_title: IaC 기반 프로젝트 리딩 (운영플랫폼 프로젝트)
        caption: Terraform, Terraform module, Azure Policy, KQL, Azure Workbook, Azure Resource Graph, Grafana, Git
        description: | # this will include new lines to allow paragraphs
          - Azure 랜딩존 기반으로 운영에 필요한 이벤트 관리, 자산현황, 구성관리, 변경관리, 거버넌스 등의 항목을 기획하여 Azure Workbook 및 Grafana 대시보드로 구현하고, Azure Policy를 사용해 클라우드 거버넌스 구현
          - 각 항목을 일관성 있게 배포하고 재사용 가능하도록 Terraform Module로 설계, 문서화 및 버전관리 적용
          - 고객 온보딩을 위해 Azure Lighthouse를 사용한 Cross-Tenant 관리 방안 연구
          - 팀내 Terraform 협업을 위해 코드 스타일 및 문서화 규칙 수립
          - 프로젝트 일정과 작업계획, 역할 분배, 주간 회의, 기술공유 리딩

          ---

      - layout: top
        title: 3. 인프라 자동화 역량
        sub_title: 인프라 자동화 업무
        caption: Shell Script, Azure DevOps, EventGrid, Functions, Azure Policy
        link: https://github.com/hyukjuns/shell-scripts/tree/main
        link_text: https://github.com/hyukjuns/shell-scripts
        description: | # this will include new lines to allow paragraphs
          - [클라우드 자산관리를 위해 Azure 이벤트 기반 서비스 및 Azure Policy로 리소스 태깅 자동화 시스템 구축](https://github.com/hyukjuns/shell-scripts/tree/main/azure_tagging_system)
          - Shell Script 기반 시간대별 가상머신 SKU 사이즈 변경 및 Start/Stop 자동화 시스템 구성
          - 클라우드 인프라 형상 관리를 위한 ARM 템플릿 추출 및 Blob 저장 자동화 시스템 구성
          - 개발팀과 협업하여 API Call을 받으면 Terraform 변수를 입력받고, 배포가 실행되는 Azure DevOps Pipeline과 Terraform Configuration 작성

          ---

      - layout: top
        title: 4. CI/CD 설계 및 활용 역량
        sub_title: Azure DevOps PoC 및 고객 교육, 기술지원
        caption: Azure DevOps Pipeline
        link: https://medium.com/@hyukjuner/azure-devops-2-tutorial-ci-cd-pipeline-6bdf3b3b6ba
        link_text: https://medium.com/@hyukjuner/azure-devops-2-tutorial-ci-cd-pipeline-6bdf3b3b6ba
        description: | # this will include new lines to allow paragraphs
          - Packer를 사용하여 Tomcat 서비스를 탑재한 가상머신 이미지 빌드, 이후 Blue/Green 전략으로 VMSS에 배포하는 CI/CD 파이프라인 구성, 부하분산 장치를 통한 트래픽 전환 가이드 제공
          - 웹 애플리케이션을 Docker 이미지로 빌드 하여, Azure Container Registry에 딜리버리하고, 승인과정을 거쳐 Azure App Service에 환경별로 배포하는 CI/CD 파이프라인 구성 및 문서화, 고객사 핸즈온 교육 진행
          - 고객사 Azure DevOps 파이프라인 트러블 슈팅 및 기술 지원, 파이프라인 구성 가이드 수행
  
  - title: Certificates
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: Cloud and DevOps
        sub_title: Microsoft Azure, Hashicorp Terraform, Kubernetes
        description: | 
          | Azure Administrator Associate        | Azure Solutions Architect Expert | Terraform Associate 003  | CKA: Certified Kubernetes Administrator | CKAD: Certified Kubernetes Application Developer
          |:-------------:|:-------------:|:------------:|:------------:|:------------:|
          | ![azureadmin](images/azure-admin.png)     | ![azuresa](images/azure-sa.png) | ![terraform](images/terraform003.png) | ![cka](images/cka.png) | ![ckad](images/ckad.png)
          | Microsoft    | Microsoft | HashiCorp | The Linux Foundation | The Linux Foundation
          | [Badge](https://www.credly.com/badges/b5616a4d-d730-4128-a07d-9e2014702bf1/public_url)    | [Badge](https://www.credly.com/badges/3ff69143-2487-4563-87a1-32a186f26578/public_url) | [Badge](https://www.credly.com/badges/fbc662fb-61ad-43c7-a5eb-a43fbe761893/public_url) | [Badge](https://www.credly.com/badges/2ef2b693-dd9b-4ca9-aa6c-88b075e5fc10/public_url) | [Badge](https://www.credly.com/badges/fcf74bd7-3dae-4fa8-b353-8152acca3d8a/public_url)

  - title: Side Projects
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: 기술블로그
        link: https://medium.com/@hyukjuner
        link_text: https://medium.com/@hyukjuner
        description: | 
          - 개인적인 학습과 업무 경험을 통해 배운 내용을 정리해 두는 장소입니다.
          - How to Guide, Tutorial, 기술 소개 등 글의 속성을 나눠 글을 작성하고 있습니다.
      - layout: left
        title: Github Repository
        link: https://github.com/hyukjuns
        link_text: https://github.com/hyukjuns
        description: | 
          - 코드를 비롯한 각종 개인 작업을 정리하고 문서화 하면서 관리하고 있습니다.
          - 업무에서 파생되거나 개인적인 호기심으로 시작한 테스트, 사이드프로젝트를 관리 하고 있습니다.
      - layout: left
        title: TIG Stack Automation
        link: https://github.com/hyukjuns/tig-packer-terraform-ansible
        link_text: GitHub - hyukjuns/tig-packer-terraform-ansible
        description: | 
          - TIG 모니터링 스택의 구축을 자동화 하기 위해 만든 사이드프로젝트 입니다.
          - Packer, Terraform, Ansible, Shell Script를 활용해서 모니터링 VM과 Telegraf, InfluxDB, Grafana 설치를 자동화하여 모니터링 환경을 빠르게 구축할 수 있도록 합니다.
  - title: Education
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: 국립한국교통대학교
        sub_title: 전자공학과 학사졸업
        caption: 2013.03 ~ 2020.02
        description: | 
          - **학부생 Programming Lab (**ESC, 2017.01~2018.07)
          - C, Java 를 사용한 머신러닝 알고리즘 학습 및 구현, 뉴럴네트워크를 활용한 화자인식 연구와 학술대회 참가
          - [(Github) **esc-machine-learning**](https://github.com/hyukjuns/esc-machine-learning)
      - layout: left
        title: 클라우드 전문교육
        sub_title: CCCR
        caption: 2020.05 ~ 2020.11
        link: https://www.cccr-edu.or.kr/board/read.jsp?id=52191&code=pds1&ch=recruit
        link_text: 교육과정 소개 링크
        description: | 
          - 리눅스 및 가상화, 오픈스택, IaC, 컨테이너 환경(Docker,K8s) 등 클라우드에 대한 전문 교육 이수, **우수 교육생 수상 및 팀프로젝트 3위** 수상
          - 팀프로젝트: Disconnect Openshift Container Platform 구축 및 DevSecOps Pipeline
          - [(Github) Disconnected-Openshift4 - Installing a cluster on bare metal in a disconnected network (2020.09 ~ 11)](https://github.com/cccr2guro-redhat/Disconnected-Openshift4)
  - title: Other Experience
    layout: text
    content: |
      - [(2022.11.10) 웨비나(Youtube) 클라우드 도입 후 고려해야 할 사항 (운영관리)](https://www.youtube.com/watch?v=ud2oFqGEhqA)
      - [(2021.05.24) 인터뷰(잡플래닛) 자유가 만든 '책임감', 성장의 밑거름이죠](https://www.jobplanet.co.kr/contents/news-1629)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
